version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0.cli-migrations
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: peeristcapstone
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS512", "key": "-----BEGIN CERTIFICATE-----\nMIIDDzCCAfegAwIBAgIJYFMZ9dQQn5qsMA0GCSqGSIb3DQEBCwUAMCUxIzAhBgNV\nBAMTGnBlZXJpc3QtY2Fwc3RvbmUuYXV0aDAuY29tMB4XDTIwMDEyMjIxMjM0M1oX\nDTMzMDkzMDIxMjM0M1owJTEjMCEGA1UEAxMacGVlcmlzdC1jYXBzdG9uZS5hdXRo\nMC5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDgy52nDRP+QMHH\nSBJ1mcRbcUUmJx6fNWxZ9s/EnnAtSjuA8HXHxQ2tYcOr/tjPf0Go7aS252a7gSlJ\nBBJmp8VI+kaH+oe/EPUdSE05B9AgogApwvCoFbQ6CkBEWvx3u51hDRjETjnh6KKa\n+KvaRcMoNJBorFrO8Ee5XZOhjZuL5l5Z0+9XXXInMDTDP4UXXliOUNR4PRRC9cND\ng8KDwpAB++Cf2Er0Uuurq9Mn6AFpwwSnAZnU0wgtvsU/t8dOVy/r0TRInlCIgl9r\nCAr+WV9bUfOdLVHcdRgdqFNqvoeOxUnfyPWdYiNEjcI02t8xnPwYSwipLBSHjxun\nEGisUfpHAgMBAAGjQjBAMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFAissa9v\nYLqxXmsNan3a/9QQ4z5RMA4GA1UdDwEB/wQEAwIChDANBgkqhkiG9w0BAQsFAAOC\nAQEAGlJXDq7XdQ8lqLoMfOGlafBdOc8eHSQozLcFGrk+azK6OP9iOwFhW9zdDZwr\nAQuuevZZca/4ouXcxCnlSPYhHDpfJAwN9Pt3RBaTQ+79bn4V6/McpEOze7TI6HG/\nKqXPwYlO+qunSEUa6pk6fUFnySqILRl+fbI40Ln/TqG1t5/9QCG0AqgYMLpuZutd\nMnMAMs5ItKHILytojTN4PeHCf4hXNclwzLMlGLl47okmYV51+vdSNqTOKsUzIJTI\nNA7sqcg17OmhTWrhrh0sLNiZOzaEtsgUAeoI8ih1jEQSA+nSaJKHLoFLJZKQThDL\nCJEuZzFi/rD7WN5pW26kk9Cf2g==\n-----END CERTIFICATE-----\n"}'
    volumes:
      - ./hasura/migrations:/hasura-migrations
volumes:
  db_data:
